###################################################
##  https://minecraft.wiki/w/Game_rule           ##
##  1.21.11+ uses snake_case gamerule names     ##
##  difficulty: peaceful, easy, normal, or hard ##
###################################################

worlds:
  '*':
    show_advancement_messages: false
    show_death_messages: false
    random_tick_speed: 0
  'world':
    difficulty: normal
    show_advancement_messages: false
    show_death_messages: false
    advance_time: false
    fall_damage: false
    fire_damage: false
    keep_inventory: true
    random_tick_speed: 0
    fire_spread_radius_around_player: 0
    mob_drops: false
    spawn_mobs: false
    block_drops: false
    advance_weather: false
    mob_griefing: false
    mob_explosion_drop_decay: false
    block_explosion_drop_decay: false
